// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "RequestMoneyFromMentor.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message RequestMoneyFromMentor
 */
export interface RequestMoneyFromMentor {
}
// @generated message type with reflection information, may provide speed optimized methods
class RequestMoneyFromMentor$Type extends MessageType<RequestMoneyFromMentor> {
    constructor() {
        super("RequestMoneyFromMentor", []);
    }
    create(value?: PartialMessage<RequestMoneyFromMentor>): RequestMoneyFromMentor {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RequestMoneyFromMentor>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestMoneyFromMentor): RequestMoneyFromMentor {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RequestMoneyFromMentor, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RequestMoneyFromMentor
 */
export const RequestMoneyFromMentor = new RequestMoneyFromMentor$Type();
